### ISSUE TITLE
More holds Special Cases

### ISSUE THREAD

**Issue by Alrandra** [AelithBlanchett/nsfwbot#11]
## Claw holds

ids 43-45

Claw-Hold 
Requirements: 8 Strength 
Description: The claw involves the attacker gripping the top of the head of the opponent with one hand and squeezing the tips of their fingers into the opponent's skull, thereby applying five different points of pressure. 
Damage: Does 5 Health Damage for 1 turn. Lower's the 'Hit dice' of "Forced Kissing", "Forced Cock Sucking" by 3 for 3 turns. 

Shoulder Claw-Hold 
Requirements: 6 Strength; 3 Endurance 
Description: Similar to a claw-hold, the attacking wrestler applies a nerve lock onto the opponent's shoulder by using their hands and fingers to dig in and compress the top of the shoulder. Usually performed with the attacking wrestler standing behind a seated opponent. 
Damage: Does 5 Health Damage for 1 turn. Lower's the 'Hit dice' of attacks using the affected arm by 3 for 3 turns. 

## Face Lock

id 51

Face Lock 
Requirements: 1 Strength; 1 Dexterity -or- 1 Agility 
Description: The wrestler faces his opponent who is bent over. The attacking wrestler tucks the opponent's head underneath his armpit and wraps his arm around the head so that the forearm is pressed against the face. The wrestler then grabs his own arm with his free hand to lock in the hold and compress the opponent's face. Similar in execution to a front chancery, the front facelock is often used as a setup for a suplex throw. 
Damage: Does no damage. If the opponent is still trapped on your next turn, gain +2 to 'Hit Dice' for any "Grapple: Throw" attack or "Forced Fingering" or Forced Cock Stroking" attacks and a +1 to 'Hit Dice' to all other attacks except for Grapple: Holds

**Comment by AelithBlanchett** [comment]
Claw Hold is now:
_Damage: Does 5 Health Damage for 1 turn. Lower's the 'Hit dice' of "Forced Kissing", "Forced Cock Sucking" by 3 for the **next** turn._

Shoulder Claw Hold is now:
_Damage: Does 5 Health Damage for 1 turn. Lower's the opponent's dexterity by one._

Face Lock is now:
_Damage: Does no damage. If the opponent is still trapped on your next turn, gain +2 to 'Hit Dice' for any "Grapple: Throw" attack or "Forced Fingering" or Forced Cock Stroking"_

I'll change the way the bot handles the bonus thingy. I'll keep you updated on it, thank you very much for your help, as always.

**Comment by Alrandra** [comment]
Okay, sound good. :)
