### ISSUE TITLE
Bondage items seem to randomly reset and never pass 1?

### ISSUE THREAD

**Issue by Pyonsuke** [AelithBlanchett/nsfwbot#30]
For example:
Attacker: !bondage
Defender now has 1/3 bondage items
Defender: !rest
Defender now has 1/3 bondage items
Attacker: !bondage
Defender now has 0/3 bondage items

It appears to happen with any action (!rest, !escape, etc)

**Comment by AelithBlanchett** [comment]
Bondage attacks are handled with the Modifiers custom array, maybe there's something wrong with the removeMod() function in Fighter.ts. I'll look into it later

**Comment by AelithBlanchett** [comment]
The latest build failed, but it's an error from Travis' side I believe.

**Comment by Pyonsuke** [comment]
Pull request #31 seems to solve this issue.

**Comment by AelithBlanchett** [comment]
I'll check that in a moment.

**Comment by Pyonsuke** [comment]
Seems to be working :+1:
