### ISSUE TITLE
Features not remaining after match starts

### ISSUE THREAD

**Issue by Pyonsuke** [AelithBlanchett/nsfwbot#49]
#47 fixed this, but it was closed instead of merged?

**Comment by AelithBlanchett** [comment]
https://github.com/AelithBlanchett/nsfwbot/pull/47#issuecomment-262870916
See my comment here,
the commit is there: https://github.com/AelithBlanchett/nsfwbot/commit/5f1913164f5cd0a8adfbca920db2ff00653caf7e

Thank you, once again.
